version: "3"


services:

  #############
  # Webserver #
  #############

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx.conf

  #############
  # Databases #
  #############

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./.docker_volumes/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=password

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./.docker_volumes/postgres:/var/lib/postgresql/data/

  phppgadmin:
    image: dockage/phppgadmin:latest
    ports:
    - 8082:80
    environment:
    - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
    - PHP_PG_ADMIN_SERVER_HOST=postgres
    - PHP_PG_ADMIN_SERVER_PORT=5432
    - PHP_PG_ADMIN_SERVER_SSL_MODE=allow
    - PHP_PG_ADMIN_SERVER_PG_DUMP_PATH=/usr/bin/pg_dump
    - PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH=/usr/bin/pg_dumpall

  ###########
  # Jupyter #
  ###########

  jupyter:
    image: jupyter/datascience-notebook:latest
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/notebooks

  ###############################
  # Doccano Labelling Interface #
  ###############################

  doccano:
    image: chakkiworks/doccano
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=password
      - DATABASE_URL=postgres://doccano:doccano@doccano-postgres:5432/doccano?sslmode=disable
    ports:
      - 8000:8000
    depends_on:
      - doccano-postgres

  doccano-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "doccano"
      POSTGRES_PASSWORD: "doccano"
      POSTGRES_DB: "doccano"
    volumes:
      - ./.docker_volumes/doccano-postgres:/var/lib/postgresql/data/


  ############
  # Metabase #
  ############

  metabase:
    image: metabase/metabase:latest
    ports:
      - 3000:3000
    depends_on:
      - metabase-postgres
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=user
      - MB_DB_PASS=password
      - MB_DB_HOST=metabase-postgres

  metabase-postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=metabase
    volumes:
      - ./.docker_volumes/metabase-postgres:/var/lib/postgresql/data/

  ###########
  # Airflow #
  ###########

  airflow-redis:
    image: 'redis:3.2.7'
    # command: redis-server --requirepass redispass

  airflow-postgres:
    image: postgres:9.6
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
    volumes:
      - ./.docker_volumes/airflow-postgres:/var/lib/postgresql/data/

  airflow-webserver:
    image: puckel/docker-airflow:1.10.3
    depends_on:
        - airflow-postgres
        - airflow-redis
    environment:
        - LOAD_EX=n
        - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - EXECUTOR=Celery
        - POSTGRES_HOST=airflow-postgres
        - REDIS_HOST=airflow-redis
        - PYTHONPATH=/code
        # - POSTGRES_USER=airflow
        # - POSTGRES_PASSWORD=airflow
        # - POSTGRES_DB=airflow
        # - REDIS_PASSWORD=redispass
    volumes:
        - ./dags:/usr/local/airflow/dags
        # Uncomment to include custom plugins
        # - ./plugins:/usr/local/airflow/plugins
        - ./src:/code/src/
    ports:
        - "8080:8080"
    command: webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3

  airflow-flower:
    image: puckel/docker-airflow:1.10.3
    depends_on:
        - airflow-redis
    environment:
        - EXECUTOR=Celery
        - REDIS_HOST=airflow-redis
        - POSTGRES_HOST=airflow-postgres
        # - REDIS_PASSWORD=redispass
    ports:
        - "5555:5555"
    command: flower

  airflow-scheduler:
    image: puckel/docker-airflow:1.10.3
    depends_on:
        - airflow-webserver
    volumes:
        - ./dags:/usr/local/airflow/dags
        # Uncomment to include custom plugins
        # - ./plugins:/usr/local/airflow/plugins
        - ./src:/code/src/
    environment:
        - LOAD_EX=n
        - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - EXECUTOR=Celery
        - POSTGRES_HOST=airflow-postgres
        - REDIS_HOST=airflow-redis
        - PYTHONPATH=/code
        # - POSTGRES_USER=airflow
        # - POSTGRES_PASSWORD=airflow
        # - POSTGRES_DB=airflow
        # - REDIS_PASSWORD=redispass
    command: scheduler

  airflow-worker:
    image: puckel/docker-airflow:1.10.3
    depends_on:
        - airflow-scheduler
    volumes:
        - ./dags:/usr/local/airflow/dags
        # Uncomment to include custom plugins
        # - ./plugins:/usr/local/airflow/plugins
        - ./src:/code/src/
    environment:
        - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - EXECUTOR=Celery
        - POSTGRES_HOST=airflow-postgres
        - REDIS_HOST=airflow-redis
        - PYTHONPATH=/code
        # - POSTGRES_USER=airflow
        # - POSTGRES_PASSWORD=airflow
        # - POSTGRES_DB=airflow
        # - REDIS_PASSWORD=redispass
    command: worker
